Add space between cancel and ban button
LemmyNet/lemmy-ui pull request #1620
Opened 2023-06-26 19:56 UTC by pascaldevink

When banning a user, the modal has two buttons: cancel and ban. These buttons are so close to each other that it's hard to see they are separate buttons.

By putting each button on their own row, there is more space between them.

Before:
![CleanShot 2023-06-26 at 20 55 06](https://github.com/LemmyNet/lemmy-ui/assets/106844/aa29be9a-d0b4-4068-9692-072159f7c609)

After:
![CleanShot 2023-06-26 at 20 53 54](https://github.com/LemmyNet/lemmy-ui/assets/106844/9cd97822-50ab-4433-beac-184d9ecd0644)

2023-06-26 20:10 UTC, dessalines requested changes

2023-06-26 20:10 UTC, dessalines commented on src/shared/components/person/profile.tsx
>              </button>
Just add mb-3 to the button, not adding a pointless row like this.

2023-06-26 20:11 UTC, jsit commented
Rather than adding an empty div, put a margin bottom and display block on the existing button.

2023-06-26 21:25 UTC, alectrocute approved these changes

2023-06-27 11:46 UTC, dessalines approved these changes

2023-06-27 11:56 UTC, merged