Add fixed width/height to `PostListing` thumbnail parent
LemmyNet/lemmy-ui pull request #1660
Opened 2023-06-27 21:32 UTC by alectrocute

Hi Lemdevs!

I noticed our thumbnails were looking inconsistent, so made an attempt to keep everything 1:1, at 5rem*5rem.

Before:

<img width="1120" alt="Screenshot 2023-06-27 at 5 32 42 PM" src="https://github.com/LemmyNet/lemmy-ui/assets/35377827/72cd4cb5-4e04-426e-88a0-66bba56a0aa1">

After:

<img width="1120" alt="Screenshot 2023-06-27 at 5 31 08 PM" src="https://github.com/LemmyNet/lemmy-ui/assets/35377827/56701128-959f-4315-b707-beda2308853a">

<img width="1120" alt="Screenshot 2023-06-27 at 5 31 11 PM" src="https://github.com/LemmyNet/lemmy-ui/assets/35377827/c56e6a1a-b4ea-4746-970a-c008d370210d">

Let me know your thoughts and/or if there's a better way to accomplish this. Our thumbnail generating function is a little bit of a mess, could be a good opportunity for refactor here.

Thanks!

2023-06-27 22:03 UTC, SleeplessOne1917 approved these changes
LGTM

2023-06-27 22:27 UTC, jsit commented
I think a col-auto next to a col-9 col-sm-10 or whatever it is might not work always. Hold pleaase

2023-06-27 22:29 UTC, jsit commented
<img width="282" alt="Screenshot 2023-06-27 at 6 28 53 PM" src="https://github.com/LemmyNet/lemmy-ui/assets/643417/8a7a13cf-1985-48cb-bc37-bc0e95ee6fad">

2023-06-27 22:31 UTC, jsit commented
Even if they're both col-auto, it doesn't work; the content part can wrap. hold please

<img width="293" alt="Screenshot 2023-06-27 at 6 30 48 PM" src="https://github.com/LemmyNet/lemmy-ui/assets/643417/b137f3ef-de91-4f75-bea9-660adaf4b5f7">

2023-06-27 22:31 UTC, jsit requested changes
needs tweaking

2023-06-27 22:36 UTC, jsit commented on src/shared/components/post/post-listing.tsx
>                  <div className="col-12 col-sm-9 col-lg-10">
```suggestion
                <div className="col flex-grow-0 post-media">
                  <div className="">{this.thumbnail()}</div>
                </div>
                <div className="col flex-grow-1">
```

2023-06-28 00:01 UTC, alectrocute commented
Made further tweaks off your work, @jsit.
<img width="1377" alt="Screenshot 2023-06-27 at 8 01 05 PM" src="https://github.com/LemmyNet/lemmy-ui/assets/35377827/52e7c23e-a092-4326-95f2-423ec7315223">
<img width="1377" alt="Screenshot 2023-06-27 at 8 01 10 PM" src="https://github.com/LemmyNet/lemmy-ui/assets/35377827/ee09aa14-b3de-4f19-a010-05efb2c3b8fe">
<img width="1377" alt="Screenshot 2023-06-27 at 8 01 14 PM" src="https://github.com/LemmyNet/lemmy-ui/assets/35377827/74b8eda3-19bc-43af-abd3-77e71c1f969b">


<img width="1377" alt="Screenshot 2023-06-27 at 8 00 55 PM" src="https://github.com/LemmyNet/lemmy-ui/assets/35377827/adcd4d06-c679-42d1-8e01-04ef8ed5d80c">

2023-06-28 00:36 UTC, jsit commented
Do we need a `mb-2` on this?

<img width="469" alt="Screenshot 2023-06-27 at 8 34 34 PM" src="https://github.com/LemmyNet/lemmy-ui/assets/643417/359f2c15-02b2-4f77-8182-cd77210320f2">

Also is `text-opacity-100-hover` doing anything on that icon?

2023-06-28 13:42 UTC, jsit requested changes
Oops sorry, I forgot to submit this review. Bootstrap already gives us overflow-hidden

2023-06-28 13:48 UTC, alectrocute commented on src/assets/css/main.css
> +.overflow-hidden {
Wasn't sure about this. I'll use the BS class instead!

2023-06-28 14:55 UTC, alectrocute commented on src/assets/css/main.css
> +.overflow-hidden {
Removed it! You were right – It was duplicative.

2023-06-28 20:42 UTC, dessalines approved these changes

2023-06-28 23:51 UTC, SleeplessOne1917 commented
@jsit Your review is still marked as need changes. Is the PR good to go now?

2023-06-29 00:04 UTC, jsit approved these changes

2023-06-29 02:44 UTC, merged