Improvements to post listings
LemmyNet/lemmy-ui pull request #536
Opened 2021-12-27 01:10 UTC by eduardog3000

* Expanded image and body now show below the rest of the listing.
  * And also offset to not be under the votes and thumbnail.
* Post title doesn't jump to a new line when you expand the image.
* Thumbnail doesn't disappear when you expand the image.
  * Does not apply on mobile since things don't jump around as much.
* Clicking expanded image opens the original in a new tab.
  * Does not apply on mobile since you can just long press.
  * Instead tapping the image closes it.
* pictrs images now prefer the original format over jpg.
* Rendering split into many functions to improve readability.
* Post actions are now on the same line as the comments button.
* Post actions now show on mobile.
* Comments button made larger.
* Expanding or contracting an image now expands or contracts the body.
* Accounts younger than 14 days will show a sprout icon on posts and comments.

2021-12-27 01:12 UTC, eduardog3000 commented
Looks like checks failed because the sprout feature includes changes to lemmy-translations.

2021-12-27 01:24 UTC, eduardog3000 commented
Just gonna leave out the sprout feature for now.

2022-01-03 17:02 UTC, dessalines requested changes
Just the one thing having to do with a new tab.

Thx for this!

2022-01-03 17:02 UTC, dessalines commented on src/shared/components/post/post-listing.tsx
> +  }
I have some preferences for which ones of these get shown by default on the full view, the mobile view, and which ones are hidden behind the 3 dot menu, but again we can wait for #449

2022-01-11 03:30 UTC, eduardog3000 commented on src/shared/components/post/post-listing.tsx
> +          <a href={this.imageSrc} class="d-inline-block" target="_blank">
Ideally the image should open in a new tab rather than losing your place in lemmy. How would you suggest going about that?

2022-01-11 06:13 UTC, dessalines commented on src/shared/components/post/post-listing.tsx
> +          <a href={this.imageSrc} class="d-inline-block" target="_blank">
I considered that sr option when I added accessibility a while ago, but unfortunately those still fail the accessibility checkers. I've removed every target blank from this codebase, even post and image links, so I wanna keep that uniform. Its also just very predictable that we don't have any, and to rely on a middle mouse click / right click / click and hold if someone wants something in a new tab.

2022-01-11 19:49 UTC, eduardog3000 commented on src/shared/components/post/post-listing.tsx
> +          <a href={this.imageSrc} class="d-inline-block" target="_blank">
I think might be worth reconsidering, but for now I'll go with it. I'll get that committed today along with resolving the merge conflicts.

2022-01-11 20:07 UTC, eduardog3000 commented
[Looks like the new build failure is due to some malicious changes in one of the libraries (`colors`).](https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/)

2022-01-12 00:53 UTC, dessalines commented
Looks good, thx!

2022-01-12 00:53 UTC, merged

2022-01-12 14:32 UTC, dessalines commented
I didn't test this thoroughly enough before merging. Post listings with bodies are broken:

![image](https://user-images.githubusercontent.com/930215/149159808-796ae3af-4071-4fd9-9d1d-43e208545645.png)