Dont allow community urls like /c/{id} (fixes #611)
LemmyNet/lemmy-ui pull request #612
Opened 2022-04-06 10:37 UTC by Nutomic

If the community identifier in url can be interpreted as a valid integer, lemmy-ui considers it as community id, which breaks things if a community has a name with only numbers.

2022-04-06 19:21 UTC, dessalines commented
This is also an issue for usernames, which is in `profile.tsx`. There are a few options:

- Now that fully qualified names are working ( IE /c/announcements@lemmy.ml ), then we can remove the number checks, and also remove numeric ID fetching from the back end completely, and from lemmy-js-client.
- Leave the numeric fetching in place, but add `/username/{number}` and `/community/{number}` in addition to the /c/ and /u/ front end routes. Then when doing that check, use the split[3] == "username" or whatever it is to determine whether it should fetch the number or string version. 

I kinda think the 2nd option is best.

2022-04-07 10:31 UTC, Nutomic commented
Removed it from profile.tsx as well. I dont think it makes sense to keep around legacy code because "it might still be used somewhere". That way we will just keep adding more logic that needs to be maintained, with no benefit for anyone.

2022-04-07 20:59 UTC, dessalines requested changes

2022-04-07 20:59 UTC, dessalines commented on src/shared/components/community/community.tsx
> +    let name_ = idOrName;
You can just do 

`let name_ = pathSplit[2];`

2022-04-07 20:59 UTC, dessalines commented on src/shared/components/person/profile.tsx
> +    form.username;
This line might have got in by accident.

2022-04-08 12:43 UTC, dessalines commented on src/shared/components/person/profile.tsx
> +    form.username = username;
This line is redundant now since you have the username in the form above.

2022-04-08 13:27 UTC, dessalines approved these changes

2022-04-08 13:29 UTC, merged