Use community display name in cross-post listings
LemmyNet/lemmy-ui pull request #660
Opened 2022-05-23 07:31 UTC by rscmbbng

Rather than the AP actor name.

2022-05-23 19:10 UTC, dessalines requested changes

2022-05-23 19:10 UTC, dessalines commented on src/shared/components/post/post-listing.tsx
> +                    <CommunityLink community={pv.community} />
Look above. CommunityLink is already a link, so don't wrap it in another <Link..

2022-06-15 15:48 UTC, dessalines requested changes
Mark as draft if you're not ready for me to review it, but also I don't know why there's so much else checked in here that have nothing to do with the change.

2022-06-15 15:48 UTC, dessalines commented on src/assets/css/themes/_variables.news.scss
> +$rounded-pill: 0.25rem;
Why is this checked in?

2022-06-15 15:48 UTC, dessalines commented on src/shared/components/home/home.tsx
> +            <main role="main" class="col-12">
Why are you removing the mobile view?

2022-06-15 15:48 UTC, dessalines commented on src/shared/components/post/post-listing.tsx
> +            <MomentTime data={post_view.post} /> ago
i18n strings, also did you look at the MomentTime component? Tell me the props on it.

2022-06-15 15:48 UTC, dessalines commented on src/shared/components/post/post-listing.tsx
> +            </div>*/}
.

2022-06-15 15:48 UTC, dessalines commented on src/shared/components/post/post-listing.tsx
> +            <span class="mr-1">Posted by</span>
i18n strings?

2022-06-15 15:48 UTC, dessalines commented on src/shared/components/post/post-listing.tsx
> +                )}
So much reorg with no explanation.

2022-06-15 18:09 UTC, rscmbbng commented
> Mark as draft if you're not ready for me to review it, but also I don't know why there's so much else checked in here that have nothing to do with the change.

Apologies, I was not aware it would add any subsequent things I'd push to main to the PR! I'm making heavily customized client so I think the majority of the changes are not relevant to you. I'll address the changes to community display names and make a separate clean PR.

2022-06-15 18:09 UTC, closed without merging

2022-06-16 14:49 UTC, dessalines commented
No probs, thx!